# Diabetes

### Import Libraries

In [62]:
import torch
import numpy as np
import pandas as pd
import torch.nn as nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler

### Load Dataset

In [5]:
data = pd.read_csv(r"C:\Users\SRKT\Desktop\Data\diabetes.csv")

In [7]:
data.head()

Number of times pregnant  Plasma glucose concentration  \
0                         6                           148   
1                         1                            85   
2                         8                           183   
3                         1                            89   
4                         0                           137   

   Diastolic blood pressure  Triceps skin fold thickness  \
0                        72                           35   
1                        66                           29   
2                        64                            0   
3                        66                           23   
4                        40                           35   

   2-Hour serum insulin  Body mass index  Age     Class  
0                     0             33.6   50  positive  
1                     0             26.6   31  negative  
2                     0             23.3   32  positive  
3                    94             28.1   21  negative  
4                   168             43.1   33  positive

### preprocessing the Data

In [8]:
data.columns

Index(['Number of times pregnant', 'Plasma glucose concentration',
       'Diastolic blood pressure', 'Triceps skin fold thickness',
       '2-Hour serum insulin', 'Body mass index', 'Age', 'Class'],
      dtype='object')

In [11]:
x = data[['Number of times pregnant', 'Plasma glucose concentration',
       'Diastolic blood pressure', 'Triceps skin fold thickness',
       '2-Hour serum insulin', 'Body mass index', 'Age']]

In [12]:
x

Number of times pregnant  Plasma glucose concentration  \
0                           6                           148   
1                           1                            85   
2                           8                           183   
3                           1                            89   
4                           0                           137   
..                        ...                           ...   
763                        10                           101   
764                         2                           122   
765                         5                           121   
766                         1                           126   
767                         1                            93   

     Diastolic blood pressure  Triceps skin fold thickness  \
0                          72                           35   
1                          66                           29   
2                          64                            0   
3                          66                           23   
4                          40                           35   
..                        ...                          ...   
763                        76                           48   
764                        70                           27   
765                        72                           23   
766                        60                            0   
767                        70                           31   

     2-Hour serum insulin  Body mass index  Age  
0                       0             33.6   50  
1                       0             26.6   31  
2                       0             23.3   32  
3                      94             28.1   21  
4                     168             43.1   33  
..                    ...              ...  ...  
763                   180             32.9   63  
764                     0             36.8   27  
765                   112             26.2   30  
766                     0             30.1   47  
767                     0             30.4   23  

[768 rows x 7 columns]

In [13]:
y = data["Class"]

In [14]:
y

0      positive
1      negative
2      positive
3      negative
4      positive
         ...   
763    negative
764    negative
765    negative
766    positive
767    negative
Name: Class, Length: 768, dtype: object

In [15]:
x1 = data.iloc[:,0:-1]

In [16]:
x1

Number of times pregnant  Plasma glucose concentration  \
0                           6                           148   
1                           1                            85   
2                           8                           183   
3                           1                            89   
4                           0                           137   
..                        ...                           ...   
763                        10                           101   
764                         2                           122   
765                         5                           121   
766                         1                           126   
767                         1                            93   

     Diastolic blood pressure  Triceps skin fold thickness  \
0                          72                           35   
1                          66                           29   
2                          64                            0   
3                          66                           23   
4                          40                           35   
..                        ...                          ...   
763                        76                           48   
764                        70                           27   
765                        72                           23   
766                        60                            0   
767                        70                           31   

     2-Hour serum insulin  Body mass index  Age  
0                       0             33.6   50  
1                       0             26.6   31  
2                       0             23.3   32  
3                      94             28.1   21  
4                     168             43.1   33  
..                    ...              ...  ...  
763                   180             32.9   63  
764                     0             36.8   27  
765                   112             26.2   30  
766                     0             30.1   47  
767                     0             30.4   23  

[768 rows x 7 columns]

In [22]:
y1 = list(data.iloc[:,-1])

In [23]:
y1

['positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',

In [19]:
x = x.values

In [24]:
x1 = x1.values

In [25]:
x1

array([[  6. , 148. ,  72. , ...,   0. ,  33.6,  50. ],
       [  1. ,  85. ,  66. , ...,   0. ,  26.6,  31. ],
       [  8. , 183. ,  64. , ...,   0. ,  23.3,  32. ],
       ...,
       [  5. , 121. ,  72. , ..., 112. ,  26.2,  30. ],
       [  1. , 126. ,  60. , ...,   0. ,  30.1,  47. ],
       [  1. ,  93. ,  70. , ...,   0. ,  30.4,  23. ]])

In [28]:
# convert string label into int
y_int = []

for s in y1:
    if s == "positive":
        y_int.append(1)
        
    else:
        y_int.append(0)

In [31]:
y_int[:10]

[1, 0, 1, 0, 1, 0, 1, 0, 1, 1]

In [36]:
y1 = np.array(y_int,dtype="float64")

In [39]:
y1.shape , x1.shape

((768,), (768, 7))

In [40]:
x1

array([[  6. , 148. ,  72. , ...,   0. ,  33.6,  50. ],
       [  1. ,  85. ,  66. , ...,   0. ,  26.6,  31. ],
       [  8. , 183. ,  64. , ...,   0. ,  23.3,  32. ],
       ...,
       [  5. , 121. ,  72. , ..., 112. ,  26.2,  30. ],
       [  1. , 126. ,  60. , ...,   0. ,  30.1,  47. ],
       [  1. ,  93. ,  70. , ...,   0. ,  30.4,  23. ]])

### Normalization all features should have range (-1,1)

In [42]:
sc = StandardScaler()
x1 = sc.fit_transform(x1)

In [43]:
x1

array([[ 0.63994726,  0.84832379,  0.14964075, ..., -0.69289057,
         0.20401277,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.69289057,
        -0.68442195, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -0.69289057,
        -1.10325546, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ...,  0.27959377,
        -0.73518964, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.69289057,
        -0.24020459,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.69289057,
        -0.20212881, -0.87137393]])

### convert our numpy array to pytorch tensor

In [48]:
x = torch.tensor(x1)
y = torch.tensor(y1).unsqueeze(1) #unsqueeze add dimensions at postion

In [49]:
x[:10],y[:10]

(tensor([[ 0.6399,  0.8483,  0.1496,  0.9073, -0.6929,  0.2040,  1.4260],
         [-0.8449, -1.1234, -0.1605,  0.5309, -0.6929, -0.6844, -0.1907],
         [ 1.2339,  1.9437, -0.2639, -1.2882, -0.6929, -1.1033, -0.1056],
         [-0.8449, -0.9982, -0.1605,  0.1545,  0.1233, -0.4940, -1.0415],
         [-1.1419,  0.5041, -1.5047,  0.9073,  0.7658,  1.4097, -0.0205],
         [ 0.3430, -0.1532,  0.2530, -1.2882, -0.6929, -0.8113, -0.2758],
         [-0.2510, -1.3425, -0.9877,  0.7191,  0.0712, -0.1260, -0.6161],
         [ 1.8278, -0.1845, -3.5726, -1.2882, -0.6929,  0.4198, -0.3608],
         [-0.5479,  2.3819,  0.0462,  1.5346,  4.0219, -0.1894,  1.6813],
         [ 1.2339,  0.1285,  1.3904, -1.2882, -0.6929, -4.0605,  1.7663]],
        dtype=torch.float64), tensor([[1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [1.]], dtype=torch.float64))

In [50]:
x.shape, y.shape

(torch.Size([768, 7]), torch.Size([768, 1]))

### Build custom Dataset

In [52]:
class Dataset(Dataset):
    def __init__(self,x,y):
        self.x = x
        self.y = y
        
    def __getitem__(self,index):
        return self.x[index],self.y[index]
    
    def __len__(self):
        return len(self.x)

In [53]:
dataset = Dataset(x,y)

In [63]:
train_loader = DataLoader(dataset=dataset,batch_size=32,shuffle=True)

### Build the Network

In [60]:
class Model(nn.Module):
    def __init__(self,input_features,output_features):
        super(Model,self).__init__()
        self.fc1 = nn.Linear(input_features,5)
        self.fc2 = nn.Linear(5,4)
        self.fc3 = nn.Linear(4,3)
        self.fc4 = nn.Linear(3,output_features)
        self.sigmoid = nn.Sigmoid()
        self.tanh = nn.Tanh()
        
    def forward(self,x):
        out = self.fc1(x)
        out = self.tanh(out)
        out = self.fc2(out)
        out = self.tanh(out)
        out = self.fc3(out)
        out = self.tanh(out)
        out = self.fc4(out)
        out = self.sigmoid(out)
        return out

In [61]:
#create the object of the network
net = Model(7,1)

#binary cross entropy 
criterion = torch.nn.BCELoss(size_average = True)

#optimzer SGD
optimizer = torch.optim.SGD(net.parameters(),lr = 0.01)

c:\python36\lib\site-packages\torch\nn\_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))


### Train the Network

In [66]:
epochs = 100

for epoch in range(100):
    for inputs,labels in train_loader:
        inputs = inputs.float()
        labels = labels.float()
        
        #Forward propagation
        outputs = net.forward(inputs)
        
        #Loss Calculation
        loss = criterion(outputs,labels)
        
        #clear the gradient buffer (w_new = w_old - lr * gradient)
        optimizer.zero_grad()
        
        # back prop
        loss.backward()  # calculateing the gradeint
        
        #update the weight
        optimizer.step()
        
        
    #Accuracy Calculations
    output = (outputs>0.5).float()
    
    accuracy = (output==labels).float().mean()
    
    print("Epoch {}/{},Loss:{:.3f},Accuracy:{:.3f}".format(epoch+1,epochs,loss,accuracy))

Epoch 1/100,Loss:0.691,Accuracy:0.688
Epoch 2/100,Loss:0.674,Accuracy:0.750
Epoch 3/100,Loss:0.692,Accuracy:0.531
Epoch 4/100,Loss:0.657,Accuracy:0.750
Epoch 5/100,Loss:0.703,Accuracy:0.500
Epoch 6/100,Loss:0.637,Accuracy:0.750
Epoch 7/100,Loss:0.699,Accuracy:0.531
Epoch 8/100,Loss:0.626,Accuracy:0.750
Epoch 9/100,Loss:0.690,Accuracy:0.562
Epoch 10/100,Loss:0.665,Accuracy:0.625
Epoch 11/100,Loss:0.730,Accuracy:0.469
Epoch 12/100,Loss:0.661,Accuracy:0.625
Epoch 13/100,Loss:0.620,Accuracy:0.719
Epoch 14/100,Loss:0.648,Accuracy:0.656
Epoch 15/100,Loss:0.615,Accuracy:0.719
Epoch 16/100,Loss:0.613,Accuracy:0.719
Epoch 17/100,Loss:0.707,Accuracy:0.531
Epoch 18/100,Loss:0.559,Accuracy:0.812
Epoch 19/100,Loss:0.677,Accuracy:0.594
Epoch 20/100,Loss:0.574,Accuracy:0.781
Epoch 21/100,Loss:0.572,Accuracy:0.781
Epoch 22/100,Loss:0.672,Accuracy:0.594
Epoch 23/100,Loss:0.640,Accuracy:0.656
Epoch 24/100,Loss:0.691,Accuracy:0.562
Epoch 25/100,Loss:0.563,Accuracy:0.781
Epoch 26/100,Loss:0.617,Accuracy:0